### ISSUE TITLE
sb-cltl2 dependency problem

### ISSUE THREAD

**Issue by atgreen** [galdor/tungsten#1]
Consider adding the following:

```
diff --git a/tungsten-core/tungsten-core.asd b/tungsten-core/tungsten-core.asd
index 8fa86b0..53211f4 100644
--- a/tungsten-core/tungsten-core.asd
+++ b/tungsten-core/tungsten-core.asd
@@ -21,6 +21,7 @@
    (:file "backtrace")
    (:file "environment")
    (:file "macros"))
+  :depends-on (#+sbcl :sb-cltl2)
   :in-order-to ((test-op (test-op "tungsten-core/test"))))
```

**Comment by galdor** [comment]
Ah you're correct, I'm used to require it in my `~/.sbclrc`. Before I fix it, I was checking the ASDF manual. Shouldn't it be `:depends-on (#+sbcl (:require :sb-cltl2))`?

**Comment by atgreen** [comment]
I don't think so.  It worked for me as written.

**Comment by galdor** [comment]
According to the ASDF documentation:

> It is good taste to use (:feature :implementation-name (:require module-name)) rather than #+implementation-name (:require module-name) to only depend on the specified module on the specific implementation that provides it. 

So it should actually be:

```
:depends-on ((:feature :sbcl (:require :sb-cltl2)))
```

Anyway it is fixed, thank you for the bug report.

**Comment by atgreen** [comment]
TIL. Thanks!
